### ISSUE TITLE
🐞 Bug Report: Parenthesis appeared when no scope is provided

### ISSUE THREAD

**Issue by VictorRos** [muandane/goji#10]
### 🐞 Describe the bug

If I'm not writing a scope, my commit contains `()` in it.

```text
dead ⚰️ (): Remove pre-push hook for branch validation
```

### 🔁 To Reproduce

- Select any type of commit
- Write a commit without a scope

### 📖 Expected behavior

I expect to not have `()` if I'm not writing a scope.

```text
dead ⚰️: Remove pre-push hook for branch validation
```

### 🌅 Screenshots

![image](https://github.com/muandane/goji/assets/6940422/304fe87f-9608-455c-bb2b-0630113fb401)

### 💻 Desktop

MacOS 13.3 (22E252)

**Comment by muandane** [comment]
Will work on it!
