### ISSUE TITLE
🐝 Feature request - Message before Scope

### ISSUE THREAD

**Issue by VictorRos** [muandane/goji#11]
### Is your feature request related to a problem? Please describe.

I only wrote few commits with `goji`.

And I'm not sure if all conventional commits should have a scope, but it's really frustrating for me to start with scope instead of message.

After selecting a commit type, I want to write the message of my commit.

So most of the time I put my message in the scope :joy:

### Describe the solution you'd like

I would like to have both actions inverted.

## Actual

1. Type commit
2. Scope
3. Message

## Proposal

1. Type commit
2. Message
3. Scope

Maybe an new option in `.goji.json` to allow both ways?

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by muandane** [comment]
Okay so for this I'll have to implement:
- the skip questions option.
- enforce [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary)
Since it's optional I'll just add a way for the commit scope to be empty rather than parenthesis when not added

**Comment by muandane** [comment]
There's an option to skip the scope question now in v0.0.1-rc4, the reason i did not change the order of the questions is because of how they are laid out in the [spec](https://www.conventionalcommits.org/en/v1.0.0/#summary), well add when i can an option to change the order of the questions if needed.
