### ISSUE TITLE
🐞 Bug Report: goji --version does not show full version

### ISSUE THREAD

**Issue by VictorRos** [muandane/goji#8]
### 🐞 Describe the bug

Installed version `0.0.1-rc2`

- Run `goji --version`
- Show `0.0.1`

It could be `0.0.1-rc`, `0.0.1-rc2` or `0.0.1` (not exist yet).

### 📖 Expected behavior

- Run `goji --version`
- Show `0.0.1-rc2`

### 🌅 Screenshots

![image](https://github.com/muandane/goji/assets/6940422/4467b617-78f6-4d1a-b6db-35fdbb6204a6)

### 💻 Desktop

MacOS 13.3 (22E252)

**Comment by muandane** [comment]
will work on it!

**Comment by muandane** [comment]
fixes will be added to v0.0.1-rc3

**Comment by VictorRos** [comment]
Ok thank you, nice reactivity ;)
